# Generated by Django 4.1.2 on 2022-10-22 13:40

from django.db import migrations, models
import sqlalchemy.sql.expression
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=sqlalchemy.sql.expression.false, primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('class_no', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
            ],
        ),
    ]
