# Generated by Django 4.1.2 on 2022-10-22 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_student_registration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_Registration',
            field=models.DateField(default=datetime.date(2022, 10, 22)),
        ),
    ]
