# Generated by Django 4.1.2 on 2022-10-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.BigIntegerField(default=20000),
            preserve_default=False,
        ),
    ]
