# Generated by Django 4.1.2 on 2022-10-23 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_Registration',
            field=models.DateField(default=datetime.date(2022, 10, 23)),
        ),
    ]
