# Generated by Django 4.1.2 on 2022-10-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_date_of_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.BigIntegerField(default=0),
        ),
    ]
