# Generated by Django 4.1.2 on 2022-10-26 11:39

import datetime
from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_student_fees_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_attendance',
            fields=[
                ('registration_id', models.CharField(editable=sqlalchemy.sql.expression.false, max_length=6, primary_key=sqlalchemy.sql.expression.true, serialize=False)),
                ('date_of_attendance', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_Registration',
            field=models.DateField(default=datetime.date(2022, 10, 26)),
        ),
    ]
